test-config:
  message: "Message from config server -common env!"

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
        exclude: restart,shutdown,threaddump,heapdump
spring:
      main:
        allow-bean-definition-overriding: true
      cloud:
        config:
          enabled: true
          username: ${gs.config.username:config-client}
          password: ${gs.config.password:config-client-password}
          uri:
            - http://${gs.config.url:localhost}:8888
          discovery:
            enabled: false
          fail-fast: false
          retry:
            initial-interval: 5000
            max-interval: 15000